Admins : 
Horlabings - Design a package for pioneers to contribute to its membership 
fee and to include :
A) Facility
b) Services & Benefits
c) Contribution to Society Back - Donations and Enviromental 
Aims / Global Help - Contribite to reduce poluution 
Force 8 / Hybridboy - Please dictate what marketing ideas to incorporate
Dewiq 12345 to Assist on Admin mainly

Under Application : Business
Usma, Lucky, Jb Timmy, Kol 4,
Need to bring forth ur ideas with 4 members to combine and contribute
on the business to gain here

We shall all.merge and start layingy 5 Feb 2023

Lastly Lucky and Force 08. Hi Buddy i need ur supertech
knowlwdge to make it Elite-Ly Cool 
